services:
  postgresDB:
    image: postgres
    container_name: postgres-database
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 123456 # 
    depends_on:
        - userservice
    ports:
        - "5432:5432"

  redisDB:
    image: redis:8.6.1-alpine
    restart: always
    container_name: redis-database
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    restart: always
    container_name: user-service
    # String for signing token (change only here)
    environment: &secret                  
        SECRET: "mysupersecret_secretsecretsecretkey!123"
    build:
      context: .
      dockerfile: UserService/Dockerfile
 
  productcatalog:
    image: ${DOCKER_REGISTRY-}productcatalog  
    restart: always
    container_name: product-catalog
    build:
      context: .
      dockerfile: ProductCatalog/Dockerfile
    depends_on:
        - userservice

  shoppingcart:
    image: ${DOCKER_REGISTRY-}shoppingcart
    restart: always
    container_name: product-catalog
    build:
      context: .
      dockerfile: ProductCatalog/Dockerfile
    depends_on:
        - userservice

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    restart: always
    container_name: api-gateway
    environment: *secret
    build:
        context: .
        dockerfile: APIGateway/Dockerfile
    ports:
        - "7777:8080"
    depends_on:
        - userservice


volumes:
    redis-data:
