services:
  postgres-user:
    image: postgres
    container_name: postgres-user
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
        - "5432:5432"
    volumes:
      - postgres-user:/data

  postgres-order:
    image: postgres
    container_name: postgres-order
    restart: always
    shm_size: 128mb
    environment:
        POSTGRES_PASSWORD: 123456
    ports:
        - "5433:5432"
    volumes:
      - postgres-order:/data

  postgres-catalog:
     image: postgres
     container_name: postgres-catalog
     restart: always
     shm_size: 128mb
     environment:
        POSTGRES_PASSWORD: 123456
     ports:
        - "5434:5432"
     volumes:
      - postgres-catalog:/data

  redisDB-cart:
    image: redis
    restart: always
    container_name: redis-database
    ports:
      - "6379:6379"
    volumes:
      - redis-cart:/data

  mongoDB-payment:
    image: mongo
    container_name: mongo-payment
    restart: always
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongoDB-payment
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongoDB:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass



  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    restart: always
    container_name: user-service
    # String for signing token (change only here)
    environment: &secret                  
        SECRET: "mysupersecret_secretsecretsecretkey!123"
    build:
      context: .
      dockerfile: UserService/Dockerfile
 
  productcatalog:
    image: ${DOCKER_REGISTRY-}productcatalog  
    restart: always
    container_name: product-catalog
    build:
      context: .
      dockerfile: ProductCatalog/Dockerfile
    depends_on:
        - userservice
        - postgres-catalog

  shoppingcart:
    image: ${DOCKER_REGISTRY-}shoppingcart
    restart: always
    container_name: shopping-cart
    build:
      context: .
      dockerfile: ShoppingCartService/Dockerfile
    depends_on:
        - userservice
        - redisDB-cart

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    restart: always
    container_name: order-service
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    depends_on:
        - userservice
        - postgres-order

  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    restart: always
    container_name: payment-service
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    depends_on:
        - userservice
        - mongoDB-payment

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    restart: always
    container_name: api-gateway
    environment: *secret
    build:
        context: .
        dockerfile: APIGateway/Dockerfile
    ports:
        - "7777:8080"
    depends_on:
        - userservice


volumes:
    redis-cart:
    postgres-order:
    postgres-user:
    postgres-catalog:
